
### **Using Python and scikit-learn for Machine Learning**

1. **We’ll use Python and the `scikit-learn` package** — one of the most popular ML libraries in Python with many built-in algorithms.

2. **To install:**

   * If using **Anaconda**:  
     `conda install scikit-learn`
   * If using **other Python setups**:  
     `pip install scikit-learn`

---

**Basic Machine Learning Workflow (with scikit-learn)**

1. **Get the data** — collect or import the dataset.
2. **Clean and format the data** — handle missing values, convert formats, scale features, etc.
3. **Split the data** — divide into:

   * **Training set** (for fitting the model)
   * **Test set** (for evaluating the model)
4. **Train the model** — fit your chosen algorithm on the training data.
5. **Test the model** — check performance on the test set.
6. **Tune the model** — adjust parameters and repeat training/testing.
7. **Deploy the final model** — once performance is acceptable.

**Note:** scikit-learn follows this structured process very cleanly with built-in functions for each step.
___

# 🎈 **Overview of the scikit-learn Process**

- **We’ll now look at an example of how to use scikit-learn.**- 
- **No need to memorize this now** — you’ll get plenty of practice in upcoming coding lessons.
  - **The goal is to give you a preview** so it won’t feel unfamiliar when you start coding the algorithms yourself.



### ✅ Steps to use **scikit-learn**

1. Every algorithm in scikit-learn is used through an **_Estimator Object_**.

2. **To use a model, first import it** using this pattern:

   ```python
   from sklearn.family import ModelName
   ```

3. **Example:**
   If using **Linear Regression**, you write:

   ```python
   from sklearn.linear_model import LinearRegression
   ```

4. Here, `linear_model` is the **model family**, and `LinearRegression` is the **estimator object (the model itself)**.

5. **Next step:** Create an instance of the model (instantiate it).





* **Estimator**

  - **Estimator parameters** can be set when creating (instantiating) a model.

  - All parameters have **default values**. You can leave them as-is or adjust them.

  - **To explore available parameters:**  

    * In Jupyter: use `Shift + Tab` after typing inside the parentheses.
    * In Colab: use `Ctrl + Space` for suggestions (or check the documentation).

  - **Example:**  

In [1]:
# from sklearn.family import ModelName
from sklearn.linear_model import LinearRegression

In [6]:
# 1. Create a Linear Regression model with a custom parameter:  
model = LinearRegression(normalize=True)

In [7]:
# 2. Then, check the model’s settings:
print(model)

LinearRegression(normalize=True)


### How can I see all the default parameters?
Following returns a Python dictionary of all parameters and their current values.

In [8]:
model.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': True,
 'positive': False}


  - **Note:** You don’t have to set parameters like `normalize=True` unless needed. Defaults usually work fine to start with.


* **Fit the model**  
  After creating your model and setting parameters, you need to **fit the model to data**.
  
  * **Important:** Always split your data into a **training set** and a **test set** before fitting.

  * Example steps:

    1. `import numpy as np` → to make some sample data.
    2. Use scikit-learn’s **train-test split** function to split your data.


  ⚠️ *Note: `cross_validation` is old and replaced by `model_selection`.*

✔️ That’s it — split your data first, then fit the model to the training set.


### creating our dataset using numpy
- We create two things:
  - X: the features (inputs)
  - y: the labels (targets)

 X and y form the basic input-output pairs for training the model.

In [10]:
import numpy as np

# each row in X has a matching value in y
X = np.arange(10).reshape((5, 2))  # 5 rows, 2 features each
y = range(5)                      # 5 labels

In [11]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
list(y)

[0, 1, 2, 3, 4]

It can be done in one line like this:

In [ ]:
X, y = np.arange(10).reshape((5, 2)), range(5)

✔️ This creates:

* `X`: 5 rows × 2 columns of numbers from 0 to 9
* `y`: numbers from 0 to 4

Both assigned together in a single line.


### Splitting the dataset  

**Using `train_test_split`:**

* You split your data into training and testing sets.  
  Use this line, and sikat learn will automatically output your _**training set**_ and  _**testing set**_.

  ```python
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
  ```

**parameters:**

* `X` is Features
* `y` is Labels
* `test_size=0.3` means **30% data for testing**, **70% for training**.
* `train_test_split` automatically splits both features and labels into training and testing parts.

**Result:**

* `X_train`, `y_train` is our _Training data_
* `X_test`, `y_test` is our _Testing data_

**Note:**
No need to memorize this now — it will become clear with practice.


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print('\nX_train\n', X_train)
print('\nX_test\n', X_test)
print('\ny_train\n', y_train)
print('\ny_test\n', y_test)


X_train
 [[2 3]
 [4 5]
 [0 1]]

X_test
 [[8 9]
 [6 7]]

y_train
 [1, 2, 0]

y_test
 [4, 3]



**Fitting the Model:**

* After splitting data, train the model using `fit()` on the training data.
  - Basically we use `model` object (Remember we instantiated it as a linear regression estimator) and 
  - then we use model.fit() and we pass `features` **X_train** along with `labels` **y_train**

* Syntax:

  ```python
  model.fit(X_train, y_train)
  ```

  * `X_train` → Training features
  * `y_train` → Training labels
  * This trains the model to learn the relationship between features and labels.


In [ ]:
model.fit(X_train, y_train)


**Making Predictions with the Model:**

* After training (fitting) the model on the training data, we can use it to make predictions on the **test data**.

* This is part of a **supervised learning** workflow, where we have both **features** and **labels**.

* In **unsupervised learning**, it's different because there are **no labels** to compare against.

* To get predicted values in supervised learning, use the `.predict()` method.

* Example:

  ```python
  predictions = model.predict(X_test)
  ```

* Here:

  * `X_test` is the test set’s features.
  * `predictions` are the model's output values based on those features.



In [ ]:
predictions = model.predict(X_test)


**Model Evaluation:**

* After making predictions, we **compare them to the actual labels** in `y_test`.
* The **evaluation method depends on the type of ML task**:

  * **Regression** -> use metrics like **MAE, MSE, RMSE**
  * **Classification** -> use **accuracy, precision, recall, F1-score**
  * **Clustering** -> use **silhouette score, inertia, ARI**
* Choose the right metric based on your problem type.
