## --------    numpy array indexing    --------
### we'll see how to index and slice numpy arrays
    # it works exactly like a normal Python list
    # Objective: How to select elements or group certain elements from a Numpy array

In [1]:
import numpy as np

In [2]:
arr_1 = np.arange(11) # numpy array of 11 elements
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# we'll use [], and slice using ':' just like python normal list
arr_1[10]   # gets the value at index 10

10

In [5]:
# use slice notation [start(inclusive) : stop(exclusive)]
arr_1[1:5]

array([1, 2, 3, 4])

In [6]:
arr_1[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
# everything UPTO
arr_1[:6]   # same as arr_1[0:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
# start and UPTO END [start(inclusive) : ]
arr_1[6:]

array([ 6,  7,  8,  9, 10])

### --------    BROADCAST ability    --------
    # numpy Array differ from python list because of BROADCAST ability 

In [4]:

# Example: if we try to assign elements from 0 to 4 as below:
arr_1[0:5] = 100
# It'll broadcast the value 100 to all the 5 elements from index 0 to 4
arr_1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### ----  slice and BROADCAST  ----

In [5]:
# altering slice of an array will affect the main array
arr_2 = np.arange(0, 11)
slice_of_arr_2 = arr_2[0:6]

# apply broadcast on slice_of_arr_2 for all of its element
slice_of_arr_2[:] = 99
print(slice_of_arr_2)
# notice the main array "arr_2" is also changed
print(arr_2)

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [ ]:
# Reason: The reason is numpy array tahes up memeory, 
    # for saving memory it's slice refer to the original array

## ----  copy()  ----


In [6]:
# if we want a COPY (not refering original array) we have to use copy() method
arr_2_copy = arr_2.copy()
arr_2_copy[0:6] = 0
print(arr_2_copy)
# notice now "arr_2" is not changed
print(arr_2)

[ 0  0  0  0  0  0  6  7  8  9 10]
[99 99 99 99 99 99  6  7  8  9 10]


___