## --------    numpy array    --------
    # We'll focus on NumPy array

    # Numpy arrays essentially come in two flavors: 
    #         vectors
    #         matrices

    # Vectors are strictly 1D arrays and 
    # matrices are 2D (but a matrix can still have only one row or one column).


    NumPy (or Numpy) is a Linear Algebra Library for Python.
    Almost all of the libraries in the PyData Ecosystem created based on NumPy
    Numpy is also incredibly fast, as it has bindings to C libraries.

    install numpy:
        conda install numpy
        pip install numpy 



In [1]:
# numpy array from a python object (such as: list)
# convert a list to a numpy array
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [2]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [3]:
arr = np.array(my_list)
arr

array([1, 2, 3])

### 2D array
    2D - array: cast a list of lists to the np.array()

In [2]:
import numpy as np
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---


## --------    numpy methods to gnertae arrays    --------
    # use numpy's built-in array generator methods (faster)
    # following are some common ways to do that:
        # from a list 
        # arange()
        # zeros()
        # ones()
        # linspace()
        # eye()
        # random.rand()
        # random.randn()
        # random.randint()

In [3]:

# np.arrange(start, stop, step) - most common & quick
    # its similar to range() method
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:

np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### for more specific type of array we can use following

In [5]:
# array of all 0
np.zeros(3)     # 1D

array([0., 0., 0.])

In [6]:
# use tuple to generate higher dimensional array
np.zeros((2,3)) # 2D by (row, column)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# array of all 1
np.ones(3)     # 1D

array([1., 1., 1.])

In [8]:
np.ones((3,4)) # 2D by (row, column)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

---

## --------    linspace()    --------


In [3]:
# it returns evenly spaced numbers between intervals
# difference between "arange() vs linspace()"
    # arange(): 3rd argument is the step-size
        # arange(start, end, stepSize)
    # linspace(): 3rd argument is number of "equally spaced points between start and end"
        # linspace(start, end, noumberOfPoints)

# 10 evenly spaced points between 0 and 5
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [4]:
np.linspace(0, 5, 100)  # 100 points

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [3]:
# "Identity matrix" using numpy
np.eye(4)   # gives 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

## ------------    random numbers    ------------
    # there are lots of ways to create an array of random numbers
    # ----  np.random.rand()  ----
    # array of given-shape of matrix with 
    # random nubers from uniform distribution over "0 to 1"

In [1]:
import numpy as np
# 1D array of 5 random numbers
np.random.rand(5)

array([0.20692678, 0.7062319 , 0.05441695, 0.50843495, 0.69580551])

In [3]:
# unlike oprevious functions, in this case we don't need to pass the tuples
    # we directly pass the size (dimensions) in seperate arguments
np.random.rand(5,5)     # 5x5 matrix of random numbers

array([[0.20132434, 0.86848189, 0.59261562, 0.86924716, 0.1003208 ],
       [0.28017324, 0.46111113, 0.1062619 , 0.82679025, 0.51415248],
       [0.59606935, 0.51262761, 0.64369043, 0.84968281, 0.11641997],
       [0.69997464, 0.38334768, 0.70704902, 0.3296237 , 0.89267612],
       [0.10306861, 0.05247973, 0.69368487, 0.47316963, 0.36907756]])

In [4]:
# 'sample' or "many samples" from GAUSSIAN or standared NORMAL distributions
    # instead of rand() we use randn()
    # this will retun numbers from "standared NORMAL distribution" centered around 0
    # instead of UNIFORM distribution over "0 to 1"
np.random.randn(2)

array([0.34071001, 0.47048468])

In [5]:
# we'll visualize GAUSSIAN or standared NORMAL distributions curves later
np.random.randn(2,4)    # 2x4 matrix of random numbers from std normal distribution
# notice agin we didn't use tuples here

array([[-0.34898898, -1.72208418,  1.30151482, -2.5733984 ],
       [ 0.82417169,  0.34943289,  1.25113725, -0.76471042]])

### ----  randint()  ----

In [4]:
# returns random integers for a LOW (inclusive) to HIGH (exclusive) 
    # for a given size (how many numbers)
    # i.e. it returns n random numbers for a given "range" and "size=n"
np.random.randint(1,100)    # returns a random number between 1 and 100

66

In [5]:
np.random.randint(1,100, 10)    # returns 10 random numbers between 1 and 100

array([27, 13, 68, 45, 90, 43, 35, 78, 60, 69])

In [2]:
# we can also import a specific function from the "random" as below
from numpy.random import randint
randint(2,10)

8

---

## --------    "attributes" and "methods" of an array    --------

In [4]:
arr_1 = np.arange(25)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [3]:
rand_arr_1 = np.random.randint(0, 50, 10)
rand_arr_1

array([32, 15,  2, 33, 43, 43, 10, 33, 30, 44])

### ----  reshape()  ----

In [4]:
# returns a new array of same data with new shape
# reshapes the 1D arry "arr_1" to a 2D 5x5 array using reshape(row, column)
arr_1.reshape(5,5)  
# notice, reshape() is a method of object "arr_1"
# youll get ERR if you won't fill out the matrix completely
    # i.e. the 1D matrix must fit into the 2D matrix
    # following gives an Value-ERR, 
        # becausewe're trying to fit a 25 size 1D matrix into 50 size 2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr_1.reshape(5,10) 
# ValueError: total size of new array

# to check: row*column = total size

### ----  max / min values & their index location  ----


In [6]:
# find the max / min value of "rand_arr_1"
rand_arr_1.max()

44

In [7]:
rand_arr_1.min()

2

In [8]:

# to return the index-location of max/min, use: argmax() and argmin()
rand_arr_1.argmax()

9

In [9]:
rand_arr_1.argmin()

2

### ----  shape info  ----


In [11]:
# we use "shape" attribute, (it's not a method)
arr_1.shape 
# the comma in (25,) indicating it's a 1D vector

(25,)

In [12]:
# following, we converted it to a 5x5 2D matrix
arr_2 = arr_1.reshape(5,5)  
arr_2.shape
# returns (5,5) i.e. it's 2D now

(5, 5)

In [6]:
# Notice the two sets of brackets
arr_1.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [8]:
arr_1.reshape(1,25).shape

(1, 25)

In [9]:
arr_1.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### ----  data-type info  ----

In [13]:
# to get the datatype of an array use "dtype" attribute
arr_2.dtype

dtype('int32')

---

# ------------    some special "numpy.random" methods    ------------

### ----  random.sample()  ----

In [2]:
from random import sample

# Prints list of random items of given length
list1 = [1, 2, 3, 4, 5] 

print(sample(list1,3))

[1, 4, 5]


## -=-=-=-    Key Differences between rand(), randn(), normal()    -=-=-=-
    
    rand():     Samples from a UNIFORM distribution between [0, 1).
    randn():    Samples from a STANDARD NORMAL distribution (mean = 0, standard deviation = 1).
    normal():   Samples from a NORMAL distribution where you can specify the mean (loc) and standard deviation (scale). 
                It is more flexible than randn() because you can change the mean and standard deviation.

### ----  numpy.random.rand()  ----

In [4]:
import numpy as np
np.random.rand(3, 2)  # Output: Random numbers from a uniform distribution between 0 and 1.

array([[0.67142282, 0.4422507 ],
       [0.41463676, 0.6604738 ],
       [0.70500499, 0.83908596]])

### ----  numpy.random.randn()  ----

In [5]:
np.random.randn(3, 2)  # Output: Random numbers from a standard normal distribution.

array([[ 1.40937653, -0.85782406],
       [-2.26114629,  0.38203261],
       [-0.46015967, -0.90486816]])

### ----  numpy.random.normal()  ----

In [6]:
np.random.normal(loc=5, scale=2, size=(3, 2))  # Output: Random numbers from a normal distribution with mean 5 and standard deviation 2.

array([[4.04890284, 2.66888632],
       [5.43366808, 4.73450077],
       [4.02394207, 4.29853112]])

___