## --------    numpy array indexing    --------
### we'll see how to index and slice numpy arrays
    # it works exactly like a normal Python list
    # Objective: How to select elements or group certain elements from a Numpy array

In [1]:
import numpy as np

In [2]:
arr_1 = np.arange(11) # numpy array of 11 elements
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# we'll use [], and slice using ':' just like python normal list
arr_1[10]   # gets the value at index 10

10

In [5]:
# use slice notation [start(inclusive) : stop(exclusive)]
arr_1[1:5]

array([1, 2, 3, 4])

In [6]:
arr_1[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
# everything UPTO
arr_1[:6]   # same as arr_1[0:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
# start and UPTO END [start(inclusive) : ]
arr_1[6:]

array([ 6,  7,  8,  9, 10])

### --------    BROADCAST ability    --------
    # numpy Array differ from python list because of BROADCAST ability 

In [4]:

# Example: if we try to assign elements from 0 to 4 as below:
arr_1[0:5] = 100
# It'll broadcast the value 100 to all the 5 elements from index 0 to 4
arr_1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### ----  slice and BROADCAST  ----

In [5]:
# altering slice of an array will affect the main array
arr_2 = np.arange(0, 11)
slice_of_arr_2 = arr_2[0:6]

# apply broadcast on slice_of_arr_2 for all of its element
slice_of_arr_2[:] = 99
print(slice_of_arr_2)
# notice the main array "arr_2" is also changed
print(arr_2)

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [ ]:
# Reason: The reason is numpy array tahes up memeory, 
    # for saving memory it's slice refer to the original array

## ----  copy()  ----


In [6]:
# if we want a COPY (not refering original array) we have to use copy() method
arr_2_copy = arr_2.copy()
arr_2_copy[0:6] = 0
print(arr_2_copy)
# notice now "arr_2" is not changed
print(arr_2)

[ 0  0  0  0  0  0  6  7  8  9 10]
[99 99 99 99 99 99  6  7  8  9 10]


___

## --------    indexing of 2D array (matrix)    --------

In [1]:
import numpy as np

# to crearte a 2D numpy array we use a list of list (nested list)
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


### There are "two general formats" to access the element of a 2D array
    # [row][column]-format
    # [row, column]-format (recommend to use)

In [2]:
# [row][column]-format
arr_2d[0][0]    # 5

5

In [3]:
arr_2d[0]       # gives entire row

array([ 5, 10, 15])

In [4]:
arr_2d[1][1]    # 25

25

In [5]:
arr_2d[2][1]    # 40

40

In [6]:
arr_2d[1][2]    # 30

30

### ----  [row, column]-format  ----
    # recommened to use

In [7]:
arr_2d[2, 1]    # 40


40

In [8]:
arr_2d[1, 2]    # 30

30

### ----  sub-matrix: chunks of an array  ----
    # getting "part of an array" instead of single element
    # use slice: to retun a sub-matrix from a matrix we use ":"


In [9]:

"""
        [ 5,10,15],
        [20,25,30],
        [35,40,45]
"""
# Example: To grab the top right corner: i.e. 10, 15, 25, 30
arr_2d[:2]          # gets the first 2 row

array([[ 5, 10, 15],
       [20, 25, 30]])

In [11]:
# arr_2d[:2][1:]      # won't gets the first 2 row and then last two columns

In [2]:
# If you want to use the arr_2d[row][column] format instead of slicing directly, 
#   you can use list-comprehension

# Note that this approach is different from slicing and may not produce the desired result directly.
# Grab the top right corner using arr_2d[row][column] format
top_right_corner = arr_2d[:2]
top_right_corner = [row[1:] for row in top_right_corner]
top_right_corner

[array([10, 15]), array([25, 30])]

In [8]:
# Convert the list of lists to a NumPy array
top_right_corner = np.array(top_right_corner)
print(top_right_corner)
top_right_corner

[[10 15]
 [25 30]]


array([[10, 15],
       [25, 30]])

In [9]:
# or we can use other format
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

---

## --------    conditional selection    --------
    # applying condition will retrun a "boolean matrix"

In [2]:

import numpy as np

In [3]:
arr_3 = np.arange(1, 11)

In [5]:
# following generates Boolean-matrix
arr_3 < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [11]:
# we can apply above "Boolean matrix" to filter elements form an array (needs to same-size & shape)
bool_arr3 = (arr_3 < 5)
print(bool_arr3)

filterArr_1 = arr_3[bool_arr3]
print(filterArr_1)

arr_4 = np.arange(31, 41)
print(arr_4)
filterArr_2 = arr_4[bool_arr3]
print(filterArr_2)

[ True  True  True  True False False False False False False]
[1 2 3 4]
[31 32 33 34 35 36 37 38 39 40]
[31 32 33 34]
