## --------    numpy array indexing    --------
### we'll see how to index and slice numpy arrays
    # it works exactly like a normal Python list
    # Objective: How to select elements or group certain elements from a Numpy array

In [2]:
import numpy as np

In [3]:
arr_1 = np.arange(11) # numpy array of 11 elements
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# we'll use [], and slice using ':' just like python normal list
arr_1[10]   # gets the value at index 10

10

In [5]:
# use slice notation [start(inclusive) : stop(exclusive)]
arr_1[1:5]

array([1, 2, 3, 4])

In [6]:
arr_1[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
# everything UPTO
arr_1[:6]   # same as arr_1[0:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
# start and UPTO END [start(inclusive) : ]
arr_1[6:]

array([ 6,  7,  8,  9, 10])

___