# ------------    numpy OPERATIONS    ------------
### Basic operations we perform on numpy array
    # Array with Array 
    # Array with Scalars 
    # Universal Array Functions

In [1]:
import numpy as np
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


## ------    Array with Array    ------


In [2]:
# we can do simple arithmetic operation with two array
# following adds "element-by-element" basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [2]:
# similarly we can do subtraction and multiplication
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [2]:
arr**2      # exponents

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## ------    scaler operation    ------

In [4]:
# Numpy basically broadcast the scaler to every element 
# the operation occured in also "element by element"
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [5]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [6]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

___

## --------    numpy warning    --------

In [ ]:
# dividing elements by 0 cause ERROR in "python"
# but "numpy" gives a warning instead of ERROR
1/0     # gives ERROR in python: ZeroDivisionError

In [ ]:
# numpy gives an "warning" but no ERROR
    # notice the first element of the "arr" is 0 and 
    # 0/0 will give a ERROR in python
    # but in "numpy" we'll get an warning instead
        # it will return "nan" for 0/0 in numpy

arr / arr       # Runtimewarning: invalid value encountered in true_divide

In [ ]:
# following returns 'inf' (infinity) for the first element when performing '1/0'
1 / arr

___

## --------    universal array function    --------
    # universal array functions are just mathematical operations
    # perform-operation & broadcast over array

In [3]:
np.sqrt(arr)    # square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)    # e^n : calculates exponent e**n for each array element

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
np.max(arr)     # maximum using numpy method

10

In [6]:
# alternatively
arr.max()     # maximum using builtin array method/property

10

### ----  trigonometric functions  ----


In [7]:
np.sin(arr)     # gets the sin value element-wise

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

### ----  logarithmic value  ----


In [ ]:
# NOTE: for 0, we'll get "-ve inf" and a RuntimeWarning for "divide by 0"
np.log(arr)     # gets the "e"-based-log, i.e. ln() value element-wise

___

# ------------    Numpy Exercises    ------------
    # create zeros, ones, scalar multiplication
    # array of integers
    # 2D matrix
    # identity matrix
    # random numbers matrix
    # evenly spaced numbers

## ----    Numpy indexing and selections    ----
    # reshape
    # select parts of matrix 
    # array functions

In [2]:
# Import NumPy as np
import numpy as np

### Create an array of 10 zeros 

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# use 2x5 size: to do that use      np.zeros( (row, column), dtype )
np.zeros((2, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
np.zeros((5, 2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])


### Create an array of 10 ones

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((2, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.ones((5, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [11]:
# Create an array of 10 fives
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### Create an array of the integers from 10 to 50

In [13]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Create an array of all the even integers from 10 to 50

In [14]:
# TRICK: use increment
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])