# ------------    numpy OPERATIONS    ------------
### Basic operations we perform on numpy array
    # Array with Array 
    # Array with Scalars 
    # Universal Array Functions

In [1]:
import numpy as np
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


## ------    Array with Array    ------


In [2]:
# we can do simple arithmetic operation with two array
# following adds "element-by-element" basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [2]:
# similarly we can do subtraction and multiplication
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## ------    scaler operation    ------

In [4]:
# Numpy basically broadcast the scaler to every element 
# the operation occured in also "element by element"
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [5]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [6]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

___

## --------    numpy warning    --------

In [ ]:
# dividing elements by 0 cause ERROR in "python"
# but "numpy" gives a warning instead of ERROR
1/0     # gives ERROR in python: ZeroDivisionError

In [ ]:
# numpy gives an "warning" but no ERROR
    # notice the first element of the "arr" is 0 and 
    # 0/0 will give a ERROR in python
    # but in "numpy" we'll get an warning instead
        # it will return "nan" for 0/0 in numpy

arr / arr       # Runtimewarning: invalid value encountered in true_divide

In [ ]:
# following returns 'inf' (infinity) for the first element when performing '1/0'
1 / arr