## --------    numpy array    --------
    # We'll focus on NumPy array

    # Numpy arrays essentially come in two flavors: 
    #         vectors
    #         matrices

    # Vectors are strictly 1D arrays and 
    # matrices are 2D (but a matrix can still have only one row or one column).


    NumPy (or Numpy) is a Linear Algebra Library for Python.
    Almost all of the libraries in the PyData Ecosystem created based on NumPy
    Numpy is also incredibly fast, as it has bindings to C libraries.

    install numpy:
        conda install numpy
        pip install numpy 



In [1]:
# numpy array from a python object (such as: list)
# convert a list to a numpy array
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [2]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [3]:
arr = np.array(my_list)
arr

array([1, 2, 3])

### 2D array
    2D - array: cast a list of lists to the np.array()

In [2]:
import numpy as np
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---


## --------    numpy methods to gnertae arrays    --------
    # use numpy's built-in array generator methods (faster)
    # following are some common ways to do that

In [3]:

# np.arrange(start, stop, step) - most common & quick
    # its similar to range() method
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:

np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### for more specific type of array we can use following

In [5]:
# array of all 0
np.zeros(3)     # 1D

array([0., 0., 0.])

In [6]:
# use tuple to generate higher dimensional array
np.zeros((2,3)) # 2D by (row, column)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# array of all 1
np.ones(3)     # 1D

array([1., 1., 1.])

In [8]:
np.ones((3,4)) # 2D by (row, column)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])