In [3]:
import numpy as np

a = [.00, .01, .02]
b = [.10, .11, .12]
c = [.20, .21, .22]

In [4]:
mat_1 = np.array([a, b, c])

In [5]:
mat_1

array([[0.  , 0.01, 0.02],
       [0.1 , 0.11, 0.12],
       [0.2 , 0.21, 0.22]])

In [1]:
# np.reshape(data, (row, column))
import numpy as np
mydata = np.arange(0, 20) # create a list of 20 numbers
print(mydata)
type(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [2]:
np.reshape(mydata, (4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
# applying order-flags 'F', 'C'
np.reshape(mydata, (4, 5), order='C')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
np.reshape(mydata, (4, 5), order='F')

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [5]:
# applying order-flags 'F', 'C'
mat_1 = np.reshape(mydata, (4, 5), order='C')
mat_2 = np.reshape(mydata, (4, 5), order='F')

In [8]:
print(mat_1[2, 4])
print(mat_2[2, 4])

14
18


In [10]:
# creating matrices from a list (no 'numpy.ndarray' TYPE)
import numpy as np
mydata_2 = list(range(20)) # create a list of 20 numbers
print(mydata_2)
type(mydata_2)    # numpy.ndarray

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


list

In [11]:
np.reshape(mydata_2, (4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
# applying order-flags 'F', 'C'
mat_1 = np.reshape(mydata_2, (4, 5), order='C')
mat_2 = np.reshape(mydata_2, (4, 5), order='F')

# getting individual element
print(mat_1[2, 4])  # 14
print(mat_2[2, 4])  # 18

14
18
