In [3]:
import numpy as np

a = [.00, .01, .02]
b = [.10, .11, .12]
c = [.20, .21, .22]

In [4]:
mat_1 = np.array([a, b, c])

In [5]:
mat_1

array([[0.  , 0.01, 0.02],
       [0.1 , 0.11, 0.12],
       [0.2 , 0.21, 0.22]])

In [1]:
# np.reshape(data, (row, column))
import numpy as np
mydata = np.arange(0, 20) # create a list of 20 numbers
print(mydata)
type(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [2]:
np.reshape(mydata, (4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
# applying order-flags 'F', 'C'
np.reshape(mydata, (4, 5), order='C')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
np.reshape(mydata, (4, 5), order='F')

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [5]:
# applying order-flags 'F', 'C'
mat_1 = np.reshape(mydata, (4, 5), order='C')
mat_2 = np.reshape(mydata, (4, 5), order='F')

In [8]:
print(mat_1[2, 4])
print(mat_2[2, 4])

14
18


In [10]:
# creating matrices from a list (no 'numpy.ndarray' TYPE)
import numpy as np
mydata_2 = list(range(20)) # create a list of 20 numbers
print(mydata_2)
type(mydata_2)    # numpy.ndarray

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


list

In [11]:
np.reshape(mydata_2, (4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
# applying order-flags 'F', 'C'
mat_1 = np.reshape(mydata_2, (4, 5), order='C')
mat_2 = np.reshape(mydata_2, (4, 5), order='F')

# getting individual element
print(mat_1[2, 4])  # 14
print(mat_2[2, 4])  # 18

14
18


In [11]:
# METHOD 2:  np.array()
import numpy as np

r1 = ["I", "am", "happy"] 
r2 = ["What", "a", "day"] 
r3 = [1, 2, 3]
# r4 = [2.5, 3.7, 3.1415, 1.618]

# create a "list-of-list"
li_li = [r1, r2, r3]

# np.array will combine this li_li into a matrix row-by-row
    # there is also type-info in "dtype"
    # also numerical data will change into "string" if strings are present
    # we can have ony one type of data in an "array"
np.array(li_li, dtype='<U5') 



array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3']], dtype='<U5')

In [13]:
# Example 2: using '<U5' dtype
import numpy as np

r1 = ["I", "am", "happy"] 
r2 = ["What", "a", "day"] 
r3 = [1, 2, 3]
r4 = [2.5, 3.7, 3.1415, 1.618]


li_li = [r1, r2, r3, r4]

np.array(li_li, dtype=object)
# array([['I', 'am', 'happy'],
#        ['What', 'a', 'day'],
#        ['1', '2', '3']], dtype='<U5') 

array([list(['I', 'am', 'happy']), list(['What', 'a', 'day']),
       list([1, 2, 3]), list([2.5, 3.7, 3.1415, 1.618])], dtype=object)

In [14]:
import numpy as np

r1 = ["I", "am", "happy"] 
r2 = ["What", "a", "day"] 
r3 = [1, 2, 3]
r4 = [2.5, 3.7, 3.1415]


li_li = [r1, r2, r3, r4]

np.array(li_li, dtype='<U5')

array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3'],
       ['2.5', '3.7', '3.141']], dtype='<U5')

In [5]:
# ------------------    Dictionaries    ------------------
import numpy as np
# ----    Games    ----
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]

In [6]:
# Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])

# acessing : But it's hard to indicate the PLAYER
print(Games[0])
print(Games[2])

print(Games[2][9])
# alternative
print(Games[2][-1])

[80 77 82 82 73 82 58 78  6 35]
[79 78 75 81 76 79 62 76 77 69]
69
69


In [1]:
# --------    How to use 'Dictionaries' to access following data ?    --------

# ----    Games    ----
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]

# The players will follow the same order
    # we'll treat each player as a ROW

# The "GAME SEASONS" will follow the same order for each Player (ROW)
    # we'll treat each game as a COL


In [2]:


# Notice the corresponding dictionaries
#Seasons
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}


In [8]:
Pdict['DwightHoward']


4

In [9]:
Games[4]

array([82, 82, 82, 79, 82, 78, 54, 76, 71, 41])

In [10]:
Games[Pdict['DwightHoward']][Sdict['2012']]
# row : Pdict['DwightHoward'
# col : Sdict['2012']

76

In [1]:

# ------------------    Matrix Operations    ------------------
# Calculate How many field goles a player scored
# get the "FieldGoals" and devide it by the played game in the "Season"
import numpy as np

# ----    Field Goals    ----
KobeBryant_FG = [978,813,775,800,716,740,574,738,31,266]
JoeJohnson_FG = [632,536,647,620,635,514,423,445,462,446]
LeBronJames_FG = [875,772,794,789,768,758,621,765,767,624]
CarmeloAnthony_FG = [756,691,728,535,688,684,441,669,743,358]
DwightHoward_FG = [468,526,583,560,510,619,416,470,473,251]
ChrisBosh_FG = [549,543,507,615,600,524,393,485,492,343]
ChrisPaul_FG = [407,381,630,631,314,430,425,412,406,568]
KevinDurant_FG = [306,306,587,661,794,711,643,731,849,238]
DerrickRose_FG = [208,208,208,574,672,711,302,0,58,338]
DwayneWade_FG = [699,472,439,854,719,692,416,569,415,509]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwayneWade_FG])


# ----    Games    ----
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
# Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])


#Seasons
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}


# by programming approach: we need to use two loops
    # devide each element of a row of "FieldGoals" by each element of a row of "Games"



In [2]:
# --------    Matrix-division    --------
# however it can be easily done by "Matrix-division"

# Ignore Error-warnings
# use np.matrix.round() instead of "round()"

import warnings
warnings.filterwarnings('ignore')

FieldGoals / Games


array([[12.225     , 10.55844156,  9.45121951,  9.75609756,  9.80821918,
         9.02439024,  9.89655172,  9.46153846,  5.16666667,  7.6       ],
       [ 7.70731707,  9.40350877,  7.8902439 ,  7.84810127,  8.35526316,
         7.13888889,  7.05      ,  6.18055556,  5.84810127,  5.575     ],
       [11.07594937,  9.8974359 , 10.58666667,  9.74074074, 10.10526316,
         9.59493671, 10.01612903, 10.06578947,  9.96103896,  9.04347826],
       [ 9.45      , 10.63076923,  9.45454545,  8.10606061,  9.97101449,
         8.88311688,  8.01818182,  9.98507463,  9.64935065,  8.95      ],
       [ 5.70731707,  6.41463415,  7.1097561 ,  7.08860759,  6.2195122 ,
         7.93589744,  7.7037037 ,  6.18421053,  6.66197183,  6.12195122],
       [ 7.84285714,  7.86956522,  7.56716418,  7.98701299,  8.57142857,
         6.80519481,  6.89473684,  6.55405405,  6.2278481 ,  7.79545455],
       [ 5.21794872,  5.953125  ,  7.875     ,  8.08974359,  6.97777778,
         5.375     ,  7.08333333,  5.88571429

In [3]:

np.matrix.round(FieldGoals / Games)

array([[12., 11.,  9., 10., 10.,  9., 10.,  9.,  5.,  8.],
       [ 8.,  9.,  8.,  8.,  8.,  7.,  7.,  6.,  6.,  6.],
       [11., 10., 11., 10., 10., 10., 10., 10., 10.,  9.],
       [ 9., 11.,  9.,  8., 10.,  9.,  8., 10., 10.,  9.],
       [ 6.,  6.,  7.,  7.,  6.,  8.,  8.,  6.,  7.,  6.],
       [ 8.,  8.,  8.,  8.,  9.,  7.,  7.,  7.,  6.,  8.],
       [ 5.,  6.,  8.,  8.,  7.,  5.,  7.,  6.,  7.,  7.],
       [ 9.,  9.,  7.,  9., 10.,  9., 10.,  9., 10.,  9.],
       [ 5.,  5.,  5.,  7.,  9.,  9.,  8., nan,  6.,  7.],
       [ 9.,  9.,  9., 11.,  9.,  9.,  8.,  8.,  8.,  8.]])

In [4]:
FieldGoalsPerGame = np.matrix.round(FieldGoals / Games)

In [5]:
FieldGoalsPerGame[Pdict['DerrickRose']][Sdict['2009']]

9.0

In [6]:
# --------------------     Normalization     --------------------
# what we are doing by the division 'FieldGoals / Games' is NORMALIZATION
    # it is useful to remove 'unwanted-flactuation' in the data
    # Eg: a player playes average 10 games in each season, but in one season he played 2 games due to injury
    # Then there will be 'unwanted-flactuation' in his total-score data.
    # to remove this kind of irregularity we need the division (total_score / played_games_in_a_season)


# ----    Minutes Played    ----
KobeBryant_MP = [3277,3140,3192,2960,2835,2779,2232,3013,177,1207]
JoeJohnson_MP = [3340,2359,3343,3124,2886,2554,2127,2642,2575,2791]
LeBronJames_MP = [3361,3190,3027,3054,2966,3063,2326,2877,2902,2493]
CarmeloAnthony_MP = [2941,2486,2806,2277,2634,2751,1876,2482,2982,1428]
DwightHoward_MP = [3021,3023,3088,2821,2843,2935,2070,2722,2396,1223]
ChrisBosh_MP = [2751,2658,2425,2928,2526,2795,2007,2454,2531,1556]
ChrisPaul_MP = [2808,2353,3006,3002,1712,2880,2181,2335,2171,2857]
KevinDurant_MP = [1255,1255,2768,2885,3239,3038,2546,3119,3122,913]
DerrickRose_MP = [1168,1168,1168,3000,2871,3026,1375,0,311,1530]
DwayneWade_MP = [2892,1931,1954,3048,2792,2823,1625,2391,1775,1971]
#Matrix
MinutesPlayed = np.array([KobeBryant_MP, JoeJohnson_MP, LeBronJames_MP, CarmeloAnthony_MP, DwightHoward_MP, ChrisBosh_MP, ChrisPaul_MP, KevinDurant_MP, DerrickRose_MP, DwayneWade_MP])


In [7]:

MinutesPlayed_PerGame = np.matrix.round(MinutesPlayed / Games)
MinutesPlayed_PerGame


array([[41., 41., 39., 36., 39., 34., 38., 39., 30., 34.],
       [41., 41., 41., 40., 38., 35., 35., 37., 33., 35.],
       [43., 41., 40., 38., 39., 39., 38., 38., 38., 36.],
       [37., 38., 36., 34., 38., 36., 34., 37., 39., 36.],
       [37., 37., 38., 36., 35., 38., 38., 36., 34., 30.],
       [39., 39., 36., 38., 36., 36., 35., 33., 32., 35.],
       [36., 37., 38., 38., 38., 36., 36., 33., 35., 35.],
       [36., 36., 35., 39., 40., 39., 39., 39., 39., 34.],
       [29., 29., 29., 37., 37., 37., 35., nan, 31., 30.],
       [39., 38., 38., 39., 36., 37., 33., 35., 33., 32.]])

In [8]:
MinutesPlayed

array([[3277, 3140, 3192, 2960, 2835, 2779, 2232, 3013,  177, 1207],
       [3340, 2359, 3343, 3124, 2886, 2554, 2127, 2642, 2575, 2791],
       [3361, 3190, 3027, 3054, 2966, 3063, 2326, 2877, 2902, 2493],
       [2941, 2486, 2806, 2277, 2634, 2751, 1876, 2482, 2982, 1428],
       [3021, 3023, 3088, 2821, 2843, 2935, 2070, 2722, 2396, 1223],
       [2751, 2658, 2425, 2928, 2526, 2795, 2007, 2454, 2531, 1556],
       [2808, 2353, 3006, 3002, 1712, 2880, 2181, 2335, 2171, 2857],
       [1255, 1255, 2768, 2885, 3239, 3038, 2546, 3119, 3122,  913],
       [1168, 1168, 1168, 3000, 2871, 3026, 1375,    0,  311, 1530],
       [2892, 1931, 1954, 3048, 2792, 2823, 1625, 2391, 1775, 1971]])

In [9]:
MinutesPlayed_PerGame[Pdict['DerrickRose']][Sdict['2009']]

37.0

In [1]:
# -----------    Mini HW    -----------
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# ----    Field Goals    ----
KobeBryant_FG = [978,813,775,800,716,740,574,738,31,266]
JoeJohnson_FG = [632,536,647,620,635,514,423,445,462,446]
LeBronJames_FG = [875,772,794,789,768,758,621,765,767,624]
CarmeloAnthony_FG = [756,691,728,535,688,684,441,669,743,358]
DwightHoward_FG = [468,526,583,560,510,619,416,470,473,251]
ChrisBosh_FG = [549,543,507,615,600,524,393,485,492,343]
ChrisPaul_FG = [407,381,630,631,314,430,425,412,406,568]
KevinDurant_FG = [306,306,587,661,794,711,643,731,849,238]
DerrickRose_FG = [208,208,208,574,672,711,302,0,58,338]
DwayneWade_FG = [699,472,439,854,719,692,416,569,415,509]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwayneWade_FG])

# ----    Field Goal Attempts    ----
KobeBryant_FGA = [2173,1757,1690,1712,1569,1639,1336,1595,73,713]
JoeJohnson_FGA = [1395,1139,1497,1420,1386,1161,931,1052,1018,1025]
LeBronJames_FGA = [1823,1621,1642,1613,1528,1485,1169,1354,1353,1279]
CarmeloAnthony_FGA = [1572,1453,1481,1207,1502,1503,1025,1489,1643,806]
DwightHoward_FGA = [881,873,974,979,834,1044,726,813,800,423]
ChrisBosh_FGA = [1087,1094,1027,1263,1158,1056,807,907,953,745]
ChrisPaul_FGA = [947,871,1291,1255,637,928,890,856,870,1170]
KevinDurant_FGA = [647,647,1366,1390,1668,1538,1297,1433,1688,467]
DerrickRose_FGA = [436,436,436,1208,1373,1597,695,0,164,835]
DwayneWade_FGA = [1413,962,937,1739,1511,1384,837,1093,761,1084]
#Matrix
FieldGoalAttempts = np.array([KobeBryant_FGA, JoeJohnson_FGA, LeBronJames_FGA, CarmeloAnthony_FGA, DwightHoward_FGA, ChrisBosh_FGA, ChrisPaul_FGA, KevinDurant_FGA, DerrickRose_FGA, DwayneWade_FGA])


np.matrix.round(FieldGoals / FieldGoalAttempts,2)*100

array([[45., 46., 46., 47., 46., 45., 43., 46., 42., 37.],
       [45., 47., 43., 44., 46., 44., 45., 42., 45., 44.],
       [48., 48., 48., 49., 50., 51., 53., 56., 57., 49.],
       [48., 48., 49., 44., 46., 46., 43., 45., 45., 44.],
       [53., 60., 60., 57., 61., 59., 57., 58., 59., 59.],
       [51., 50., 49., 49., 52., 50., 49., 53., 52., 46.],
       [43., 44., 49., 50., 49., 46., 48., 48., 47., 49.],
       [47., 47., 43., 48., 48., 46., 50., 51., 50., 51.],
       [48., 48., 48., 48., 49., 45., 43., nan, 35., 40.],
       [49., 49., 47., 49., 48., 50., 50., 52., 55., 47.]])