In [3]:
import numpy as np

a = [.00, .01, .02]
b = [.10, .11, .12]
c = [.20, .21, .22]

In [4]:
mat_1 = np.array([a, b, c])

In [5]:
mat_1

array([[0.  , 0.01, 0.02],
       [0.1 , 0.11, 0.12],
       [0.2 , 0.21, 0.22]])

In [1]:
# np.reshape(data, (row, column))
import numpy as np
mydata = np.arange(0, 20) # create a list of 20 numbers
print(mydata)
type(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [2]:
np.reshape(mydata, (4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
# applying order-flags 'F', 'C'
np.reshape(mydata, (4, 5), order='C')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
np.reshape(mydata, (4, 5), order='F')

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [5]:
# applying order-flags 'F', 'C'
mat_1 = np.reshape(mydata, (4, 5), order='C')
mat_2 = np.reshape(mydata, (4, 5), order='F')

In [8]:
print(mat_1[2, 4])
print(mat_2[2, 4])

14
18


In [10]:
# creating matrices from a list (no 'numpy.ndarray' TYPE)
import numpy as np
mydata_2 = list(range(20)) # create a list of 20 numbers
print(mydata_2)
type(mydata_2)    # numpy.ndarray

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


list

In [11]:
np.reshape(mydata_2, (4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
# applying order-flags 'F', 'C'
mat_1 = np.reshape(mydata_2, (4, 5), order='C')
mat_2 = np.reshape(mydata_2, (4, 5), order='F')

# getting individual element
print(mat_1[2, 4])  # 14
print(mat_2[2, 4])  # 18

14
18


In [11]:
# METHOD 2:  np.array()
import numpy as np

r1 = ["I", "am", "happy"] 
r2 = ["What", "a", "day"] 
r3 = [1, 2, 3]
# r4 = [2.5, 3.7, 3.1415, 1.618]

# create a "list-of-list"
li_li = [r1, r2, r3]

# np.array will combine this li_li into a matrix row-by-row
    # there is also type-info in "dtype"
    # also numerical data will change into "string" if strings are present
    # we can have ony one type of data in an "array"
np.array(li_li, dtype='<U5') 



array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3']], dtype='<U5')

In [13]:
# Example 2: using '<U5' dtype
import numpy as np

r1 = ["I", "am", "happy"] 
r2 = ["What", "a", "day"] 
r3 = [1, 2, 3]
r4 = [2.5, 3.7, 3.1415, 1.618]


li_li = [r1, r2, r3, r4]

np.array(li_li, dtype=object)
# array([['I', 'am', 'happy'],
#        ['What', 'a', 'day'],
#        ['1', '2', '3']], dtype='<U5') 

array([list(['I', 'am', 'happy']), list(['What', 'a', 'day']),
       list([1, 2, 3]), list([2.5, 3.7, 3.1415, 1.618])], dtype=object)

In [14]:
import numpy as np

r1 = ["I", "am", "happy"] 
r2 = ["What", "a", "day"] 
r3 = [1, 2, 3]
r4 = [2.5, 3.7, 3.1415]


li_li = [r1, r2, r3, r4]

np.array(li_li, dtype='<U5')

array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3'],
       ['2.5', '3.7', '3.141']], dtype='<U5')

In [3]:
# ------------------    Dictionaries    ------------------
import numpy as np
# ----    Games    ----
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]

In [4]:
# Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])

# acessing : But it's hard to indicate the PLAYER
print(Games[0])
print(Games[2])

print(Games[2][9])
# alternative
print(Games[2][-1])

[80 77 82 82 73 82 58 78  6 35]
[79 78 75 81 76 79 62 76 77 69]
69
69
